### PR TITLE
Tweak build.sbt

### PR DESCRIPTION
**Pull request by fabianhjr-dealengine**

### CODE REVIEW

**Comment by IvanAtDealEngine** [comment]
1666007823_cms1 copy
@fabianhjr-dealengine

**Review by ivanmoreau — APPROVED** [review]
Ok kid.

**Review by ivanmoreau — APPROVED** [review]
OK KID.

**Review by ivanmoreau — APPROVED** [review]
LGTM?

**Review by ivanmoreau — APPROVED** [review]
UwU

**Review by ivanmoreau — APPROVED** [review]
UnU

**Review by ivanmoreau — APPROVED** [review]
Inserte meme de “wey ya” u.u

**Pull request merged**
